In [1]:
'''NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.'''

'NumPy is a Python library used for working with arrays.\n\nIt also has functions for working in domain of linear algebra, fourier transform, and matrices.\n\nNumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.\n\nNumPy stands for Numerical Python.'

In [2]:
'''In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.'''

'In Python we have lists that serve the purpose of arrays, but they are slow to process.\n\nNumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\n\nThe array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.\n\nArrays are very frequently used in data science, where speed and resources are very important.'

In [3]:
'''NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

'''

'NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.\n\nThis behavior is called locality of reference in computer science.\n\nThis is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.\n\n'

In [4]:
'''Why Numpy is faster?
Faster to read bytes of memory.
No type checking when iterating through objects.
User contiguous memory.
'''

'Why Numpy is faster?\nFaster to read bytes of memory.\nNo type checking when iterating through objects.\nUser contiguous memory.\n'

In [5]:
'''Applications of Numpy:
Plotting(Matplotlib)
Mathematics (MATLAB experiment)
Backend(Pandas,Connect4)
Machine Learning
'''

'Applications of Numpy:\nPlotting(Matplotlib)\nMathematics (MATLAB experiment)\nBackend(Pandas,Connect4)\nMachine Learning\n'

In [6]:
import numpy as np      #inport of numpy library

In [7]:
a=np.array([1,2,3])    #initialisation of one d array
print(a)

[1 2 3]


In [8]:
b=np.array([[9.0,7.0,7.0],[6.0,7.0,8.0]])   #initialisation of 2d array
print(b)

[[9. 7. 7.]
 [6. 7. 8.]]


In [9]:
#Get Dimension
a.ndim

1

In [10]:
b.ndim

2

In [11]:
#Get Shape
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
#Get Type
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('float64')

In [15]:
#Get Size by data type
a.itemsize    #returns the size (in bytes) of each element of a NumPy array

4

In [16]:
b.itemsize

8

In [17]:
#Get Size by number of elements
a.size

3

In [18]:
b.size

6

In [19]:
#Get Total size
a.size + a.itemsize

7

In [20]:
b.size + b.itemsize

14

In [21]:
#Get Total Size (second way returns total size in bytes )
a.nbytes

12

In [22]:
b.nbytes

48