In [ ]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4,5,6,7],[7,8,9,4,5,6,1]])
print(a)

[[1 2 3 4 5 6 7]
 [7 8 9 4 5 6 1]]


In [3]:
a.ndim

2

In [4]:
a.shape

(2, 7)

In [5]:
a.dtype

dtype('int32')

In [6]:
a.size

14

In [7]:
a.nbytes

56

In [8]:
a.itemsize

4

In [9]:
a.size + a.itemsize

18

In [10]:
#Get a specific element [r , c] r-->row , c-->index number
a[1,5]

6

In [11]:
a[0,4]

5

In [12]:
a[0,0]

1

In [13]:
a[0:]

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 8, 9, 4, 5, 6, 1]])

In [14]:
a[:1]

array([[1, 2, 3, 4, 5, 6, 7]])

In [15]:
a[1:]

array([[7, 8, 9, 4, 5, 6, 1]])

In [16]:
#Get a specific column
a[:,2]

array([3, 9])

In [17]:
a[:,5]

array([6, 6])

In [18]:
a[:,1]

array([2, 8])

In [19]:
#Getting a little more fancy[startindex:endindex:stepssize]
a[0,1:6:2]

array([2, 4, 6])

In [20]:
a[1,1:6:2]

array([8, 4, 6])

In [21]:
a[1,1:-1:2]

array([8, 4, 6])

In [22]:
print(a)
a[0,6]=15
print(a)

[[1 2 3 4 5 6 7]
 [7 8 9 4 5 6 1]]
[[ 1  2  3  4  5  6 15]
 [ 7  8  9  4  5  6  1]]


In [23]:
#to change entire column
print(a)
a[:,2]=5
print(a)
a[:2,4]=[1,1]
print(a)

[[ 1  2  3  4  5  6 15]
 [ 7  8  9  4  5  6  1]]
[[ 1  2  5  4  5  6 15]
 [ 7  8  5  4  5  6  1]]
[[ 1  2  5  4  1  6 15]
 [ 7  8  5  4  1  6  1]]


In [24]:
#3d Example
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
#to access specific element
d[0,1,1]

4

In [26]:
d[1,0,1]

6

In [27]:
d[:,0,:]    #access entire first row of array

array([[1, 2],
       [5, 6]])

In [28]:
d[:,1,:]    #access entire second row of array

array([[3, 4],
       [7, 8]])

In [29]:
d[:,0,1]    #access second element of first row

array([2, 6])

In [30]:
#replace rows and columns
d[:,0,:]=[[9,9],[8,8]]

In [31]:
d[1,1,1]   

8

In [32]:
d

array([[[9, 9],
        [3, 4]],

       [[8, 8],
        [7, 8]]])