In [1]:
import numpy as np

In [2]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [5]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [6]:
#Any other number
np.full((3,3) , 7) 

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:
np.full((2,2),99 , dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [8]:
a=np.array([[1,2,3,4,5,6,7],[7,8,9,4,5,6,1]])

In [9]:
#Any other number(full_like)     #make entite array in a single number
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [10]:
np.full_like(a,1)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [11]:
np.full(a.shape,3)       #make entire array in a single number

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [12]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.89908289, 0.71979784],
       [0.28959818, 0.58486387],
       [0.94925081, 0.2419088 ],
       [0.50677582, 0.80873726]])

In [13]:
np.random.rand(3,2,4)

array([[[0.72732822, 0.78976148, 0.26749371, 0.5549363 ],
        [0.83521369, 0.3076769 , 0.52834096, 0.36321148]],

       [[0.37764011, 0.46420615, 0.79342774, 0.87174986],
        [0.0845981 , 0.19450707, 0.92153518, 0.14848976]],

       [[0.59753764, 0.32335844, 0.74241114, 0.92122863],
        [0.47707011, 0.99531174, 0.31418319, 0.41864895]]])

In [14]:
np.random.random_sample(a.shape)

array([[0.42846694, 0.73220779, 0.63588123, 0.55999398, 0.18743049,
        0.85035143, 0.57465231],
       [0.14882386, 0.72465891, 0.66383795, 0.49099069, 0.67762087,
        0.91512229, 0.38714811]])

In [15]:
#Random Integer Values
np.random.randint(2,size=(3,3))    #2-->start value

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [16]:
np.identity(3)    #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
a=np.array([1,2,3])    #1D array
print(a)

[1 2 3]


In [18]:
b=np.array([[1,2,3]])     #2D array
print(b)

[[1 2 3]]


In [19]:
arr=np.array([[1,2,3]])   #if it is 1D array than output will be [1 1 1 2 2 2 3 3 3]
r1=np.repeat(arr , 3 , axis=0)    #3-->number of times we want array in output , it can be 1,2,4 etc.
print(r1)                        # the first running vertically downwards across rows (axis 0), 
                                 #    and the second running horizontally across columns (axis 1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
output= np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#copy entire array to another
a=np.array([1,2,3])
print(a)
b=a
print(b)
b[0]=100
print(b)
print(a)   #here a also gets changed.

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


In [22]:
#to avoid change of a we use following code.
a=np.array([1,2,3])
print(a)
b=a.copy()
b[2]=100
print(b)
print(a)  #here a is not changed.

[1 2 3]
[  1   2 100]
[1 2 3]
