In [1]:
import numpy as np

In [2]:
b=np.array([[1,2,3,4,],[5,6,7,8]])
print(b)
print(b.shape)

print()

a=b.reshape((4,2))    #reshape the matrices
print(a)

print()

c=b.reshape((2,2,2))
print(c)

d=b.reshape((2,3))   #gives error because values don't fit in 2*3 matrix
print(d)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [ ]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

In [ ]:
#Horizontal stack
h1=np.ones((2,4))
h2=np.full((2,4),7)

np.hstack((h1,h2))