##### Mathematics

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a+2    #add 2 to each element of a

array([3, 4, 5, 6])

In [3]:
a-2  #subtract 2 from each element

array([-1,  0,  1,  2])

In [4]:
a/2    #divide each number by 2

array([0.5, 1. , 1.5, 2. ])

In [5]:
a//2   #modulus of each element

array([0, 1, 1, 2], dtype=int32)

In [6]:
a*2    #multiply each element by 2

array([2, 4, 6, 8])

In [7]:
print(a)
a += 2      
print(a)

[1 2 3 4]
[3 4 5 6]


In [8]:
a -= 1
print(a)

[2 3 4 5]


In [9]:
a *=2
print(a)

[ 4  6  8 10]


In [10]:
b=np.array([1,0,1,0])    
a+b               #add 2 arrays

array([ 5,  6,  9, 10])

In [11]:
a**2

array([ 16,  36,  64, 100], dtype=int32)

In [12]:
#take the sin of all values
np.sin(a)

array([-0.7568025 , -0.2794155 ,  0.98935825, -0.54402111])

In [13]:
np.cos(a)

array([-0.65364362,  0.96017029, -0.14550003, -0.83907153])

###### Linear Algebra    https://numpy.org/doc/stable/reference/routines.linalg.html

In [14]:
#matrix multiplication (elememt to element)when rows and columns are same in matrices.
a=np.ones((3,2))
print(a)

print() 

b=np.full((3,2),2)
print(b)

print()

c=np.full((3,2),3)
print(c)

a*b*c

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[2 2]
 [2 2]
 [2 2]]

[[3 3]
 [3 3]
 [3 3]]


array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [15]:
#matrix multiplication when rows and columns are different in 2 matrices.
a=np.ones((2,3))
print(a)

print() 

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [16]:
#Find the Determinant
c=np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [17]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(s)

1

In [19]:
np.min(s,axis=0)

array([1, 2, 3])

In [20]:
np.min(s,axis=1)

array([1, 4])

In [21]:
np.max(s)

6

In [22]:
np.max(s,axis=1)

array([3, 6])

In [23]:
np.sum(s)

21