#### Load data from file

In [1]:
import numpy as np

In [2]:
#File must be in folder where you are working
np.genfromtxt('Text.txt', delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.,  7.,  8.,  9.,  7.,  8.,  7.,  8.,  9.,
         5., 11.,  2.,  5.,  3.,  1.,  4.],
       [ 7.,  8.,  9.,  5.,  4.,  6.,  1.,  2.,  3.,  2.,  1., 23.,  1.,
         2.,  4., 51.,  3.,  2.,  5.,  4.],
       [ 4.,  5.,  6.,  6.,  5.,  5.,  5., 55.,  5.,  1.,  2.,  3.,  1.,
        47.,  8., 12., 15., 18.,  1.,  4.]])

In [3]:
f=np.genfromtxt('Text.txt', delimiter=',')
f.astype('int32')    #makes a copy of f and convert all data to integer type , not replaces original f

array([[ 1,  2,  3,  4,  5,  7,  8,  9,  7,  8,  7,  8,  9,  5, 11,  2,
         5,  3,  1,  4],
       [ 7,  8,  9,  5,  4,  6,  1,  2,  3,  2,  1, 23,  1,  2,  4, 51,
         3,  2,  5,  4],
       [ 4,  5,  6,  6,  5,  5,  5, 55,  5,  1,  2,  3,  1, 47,  8, 12,
        15, 18,  1,  4]])

In [4]:
f=np.genfromtxt('Text.txt', delimiter=',')
a=f.astype('int32')    #makes a copy of f and convert all data to integer type , not replaces original f
print(a)    #prints values without commas

[[ 1  2  3  4  5  7  8  9  7  8  7  8  9  5 11  2  5  3  1  4]
 [ 7  8  9  5  4  6  1  2  3  2  1 23  1  2  4 51  3  2  5  4]
 [ 4  5  6  6  5  5  5 55  5  1  2  3  1 47  8 12 15 18  1  4]]


In [5]:
 print(f)        #prints values without commas

[[ 1.  2.  3.  4.  5.  7.  8.  9.  7.  8.  7.  8.  9.  5. 11.  2.  5.  3.
   1.  4.]
 [ 7.  8.  9.  5.  4.  6.  1.  2.  3.  2.  1. 23.  1.  2.  4. 51.  3.  2.
   5.  4.]
 [ 4.  5.  6.  6.  5.  5.  5. 55.  5.  1.  2.  3.  1. 47.  8. 12. 15. 18.
   1.  4.]]


In [6]:
f   #prints original f with commas

array([[ 1.,  2.,  3.,  4.,  5.,  7.,  8.,  9.,  7.,  8.,  7.,  8.,  9.,
         5., 11.,  2.,  5.,  3.,  1.,  4.],
       [ 7.,  8.,  9.,  5.,  4.,  6.,  1.,  2.,  3.,  2.,  1., 23.,  1.,
         2.,  4., 51.,  3.,  2.,  5.,  4.],
       [ 4.,  5.,  6.,  6.,  5.,  5.,  5., 55.,  5.,  1.,  2.,  3.,  1.,
        47.,  8., 12., 15., 18.,  1.,  4.]])

####  Boolean masking and Advanced indexing

In [7]:
f>9   #return true at value greater than 9 else false

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False,
        False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False,  True,  True,  True,
        False, False]])

In [8]:
f[f>10]   # returns value greater than 10 in f

array([11., 23., 51., 55., 47., 12., 15., 18.])

In [9]:
#You can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
c=[[0,1,8]]
print(c)

b=a[[5]]
print(b)

[[0, 1, 8]]
[6]


In [10]:
np.any(f>50,axis=0)  #checks vertically

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False])

In [11]:
np.any(f>50,axis=1)    #checks horizontally

array([False,  True,  True])

In [12]:
np.all(f>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [13]:
((f>50) & (f<100))    #and

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False]])

In [14]:
(~(f>50) & (f<100))   #not

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]])

In [15]:
((f>50) | (f<100))   #or

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]])

In [16]:
a=([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25],
 [26, 27, 28, 29, 30]]